import * as esbuild from 'esbuild';
import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { rm } from 'node:fs/promises';
import path from 'node:path';

// JS bundle
await rm('../server/static/chunks', { recursive: true, force: true });
const js = await esbuild.build({
  metafile: true,
  entryPoints: { bundle: 'main.ts' },
  bundle: true,
  minify: true,
  outdir: '../server/static',
  entryNames: '[name]',
  chunkNames: 'chunks/[name]-[hash]',
  splitting: true,
  format: 'esm',
  target: 'es2020',
});

// CSS bundle (github-markdown-css + KaTeX with inlined fonts)
const css = await esbuild.build({
  metafile: true,
  entryPoints: ['main.css'],
  bundle: true,
  minify: true,
  outfile: '../server/static/bundle.css',
  loader: {
    '.woff2': 'dataurl',
    '.woff': 'dataurl',
    '.ttf': 'dataurl',
  },
});

// License notices for every bundled npm package. MIT, ISC and BSD require the
// copyright and permission notice to travel with copies; minified bundles
// drop most of them.
const packageDirs = new Set();
for (const meta of [js.metafile, css.metafile]) {
  for (const input of Object.keys(meta.inputs)) {
    const match = input.match(/^(.*node_modules\/(?:@[^/]+\/)?[^/]+)\//);
    if (match) packageDirs.add(match[1]);
  }
}
const notices = new Map();
for (const dir of packageDirs) {
  const pkg = JSON.parse(readFileSync(path.join(dir, 'package.json'), 'utf8'));
  const id = `${pkg.name}@${pkg.version}`;
  if (notices.has(id)) continue;
  const licenseFile = readdirSync(dir).find((name) => /^(licen[cs]e|copying|notice)(\.|$)/i.test(name));
  notices.set(
    id,
    licenseFile
      ? readFileSync(path.join(dir, licenseFile), 'utf8').trim()
      : `License: ${pkg.license ?? 'unknown'} (no license file in the package)`,
  );
}
writeFileSync(
  '../server/static/THIRD_PARTY_NOTICES.txt',
  [
    'Third-party software bundled into server/static (bundle.js, chunks/, bundle.css).',
    'Generated by client/build.mjs; do not edit.',
    '',
    ...[...notices.keys()].sort().flatMap((id) => ['='.repeat(72), id, '', notices.get(id), '']),
  ].join('\n'),
);
